MODULE Elibest;

REQUIRE Eval, ProcessMonitor, Backup, Chat, Documentation,
        MasterDataP,
        Inventory,
        Invoicing, InvoicingInventory,
        Purchase,
        Sales,
        Retail,
        Manufacturing,
        ProjectManagement,
        HumanResources,
        CRM,
        Fleet,
        BillReceiptCost, BillReceiptCostService, // initialize after Purchase


        OperationTypes, WorkOrderOperationCustom, ManufacturingOrderInvCustom, ManufacturingOrderLotCustom,
        WorkOrderStatusCustom, WorkOrderResCustom;
