MODULE ManufacturingOrderInvCustom;

REQUIRE ManufacturingOrderInv, BomCustom, WorkOrderOperationCustom;

NAMESPACE Manufacturing;

locationSource = DATA Location (ConsumedLine);
locationResult = DATA Location (ConsumedLine);

fill(ConsumedLine cl, ComponentLine l) +{
    locationSource(cl) <- overLocationSource(l);
    locationResult(cl) <- overLocationSource(l);
}

locationResult = ABSTRACT Location (ManufacturingOrderInvCustom);
locationSource = ABSTRACT Location (ManufacturingOrderInvLedgerCustom);
locationSource = ABSTRACT Location (ManufacturingOrderInvLedgerIntermediate);

CLASS ManufacturingOrderInvCustom 'Оприходывание полуфабриката' : InvLedger;
manILedger = AGGR ManufacturingOrderInvCustom WHERE done(WorkStep line) AND item(line) IS Product;

type(ManufacturingOrderInvCustom l) += nameType(manufacturingOrder(line(l)));

active(ManufacturingOrderInvCustom l) += active(line(l));
dateTime(ManufacturingOrderInvCustom l) += executionDateTime(line(l));
toLocation(ManufacturingOrderInvCustom l) += OVERRIDE locationResult(l), locationResult(line(l));

product(ManufacturingOrderInvCustom l) += item(line(l)) AS Product;
quantity(ManufacturingOrderInvCustom l) += quantity(line(l));

number(ManufacturingOrderInvCustom l) += number(manufacturingOrder(line(l)));

edit (ManufacturingOrderInvCustom l) + { edit(manufacturingOrder(line(l))); }

CLASS ManufacturingOrderInvLedgerCustom 'Consumed materials' : InvLedger;
manInvLedger = AGGR ManufacturingOrderInvLedgerCustom WHERE done(WorkStep ws) AND sourceLine(ConsumedLine line) = ws AND NOT isFinishWorkStep(ws) AND item(line)  IS Product;

type(ManufacturingOrderInvLedgerCustom l) += nameType(manufacturingOrder(line(l)));

active(ManufacturingOrderInvLedgerCustom l) += active(ws(l));
dateTime(ManufacturingOrderInvLedgerCustom l) += executionDateTime(line(l));
fromLocation(ManufacturingOrderInvLedgerCustom l) += OVERRIDE locationSource(l), locationResult(line(l));

product(ManufacturingOrderInvLedgerCustom l) += item(line(l)) AS Product;
quantity(ManufacturingOrderInvLedgerCustom l) += toConsume(line(l));

number(ManufacturingOrderInvLedgerCustom l) += number(manufacturingOrder(line(l)));

edit (ManufacturingOrderInvLedgerCustom l) + { edit(manufacturingOrder(line(l))); }

CLASS ManufacturingOrderInvLedgerIntermediate 'Списание полуфабриката' : InvLedger;
manInvLedger = AGGR ManufacturingOrderInvLedgerIntermediate WHERE done(WorkStep ws) AND parent(WorkStep line) = ws AND item(line) IS Product;

type(ManufacturingOrderInvLedgerIntermediate l) += nameType(manufacturingOrder(line(l)));

active(ManufacturingOrderInvLedgerIntermediate l) += active(ws(l));
dateTime(ManufacturingOrderInvLedgerIntermediate l) += executionDateTime(line(l));
fromLocation(ManufacturingOrderInvLedgerIntermediate l) += OVERRIDE locationSource(l), locationResult(line(l));

product(ManufacturingOrderInvLedgerIntermediate l) += item(line(l)) AS Product;
quantity(ManufacturingOrderInvLedgerIntermediate l) += quantity(line(l));

number(ManufacturingOrderInvLedgerIntermediate l) += number(manufacturingOrder(line(l)));

edit (ManufacturingOrderInvLedgerIntermediate l) + { edit(manufacturingOrder(line(l))); }