MODULE WorkOrderOperationCustom;

REQUIRE WorkOrderOperation;

NAMESPACE Manufacturing;

CLASS ABSTRACT OperationTree;

EXTEND CLASS WorkOrder: OperationTree;
EXTEND CLASS Bom: OperationTree;

// Условие прямой связи: b - это вложенная спецификация в строке компонента спецификации p
isDirectParent (Bom b, Bom p) = GROUP SUM 1 IF b == nestedBom(ComponentLine cl) AND p == bom(cl);

// Рекурсивный уровень: 
// 0 уровень - сам корень, 1 - прямые дети, 2 - внуки и т.д.
level (Bom child, Bom parent) = RECURSION 1l IF child IS Bom AND parent == child
    STEP 2l IF isDirectParent($parent, parent);



parent = ABSTRACT OperationTree(OperationTree, ManufacturingOrder);
parent(WorkOrder o, ManufacturingOrder mo) += bom(o) IF manufacturingOrder(o) = mo;
parent(Bom b, ManufacturingOrder mo) += GROUP MAX Bom bb IF bom(ComponentLine cl) == bb AND nestedBom(cl) == b AND level(bb, bom(mo)) AND b != bom(mo);

name = ABSTRACT ISTRING[100] (OperationTree);
name(WorkOrder o) += name(o);
name(Bom b) += name(b);


EXTEND FORM manufacturingOrder
    TREE workOrderOperation opt = OperationTree PARENT parent(opt, o)
    PROPERTIES(opt) name, imagedNameStatus BACKGROUND colorStatus(opt), nameWorkCenter, startDate, startTime, duration, descriptionBom
    FILTERS manufacturingOrder(opt) = o OR level(opt, bom(o))
;

DESIGN manufacturingOrder {
    details {
        //REMOVE BOX(wo); 
        MOVE BOX(TREE workOrderOperation) { caption = badged('Work orders', countWorkOrder(o)); }
    }
}



